<?php

/**
 * @file
 * The improved_multi_select module main php code
 */

/**
 * Implementation of hook_init().
 */
function improved_multi_select_init() {
  $is_enabled = FALSE;
  if (variable_get('improved_multi_select:isall', 0)) {
    $is_enabled = TRUE;
  }
  else {
    $arg = arg();
    if (isset($arg[0]) and !($arg[0] == 'system' or $arg[0] == 'public')) {
      if ($url = variable_get('improved_multi_select:url', '')) {
        if (drupal_match_path($_GET['q'], $url)) {
          $is_enabled = TRUE;
        }
      }
    }
  }
  if ($is_enabled) {
    drupal_add_css(drupal_get_path('module', 'improved_multi_select') .'/improved_multi_select.css');
    drupal_add_js(drupal_get_path('module', 'improved_multi_select') .'/improved_multi_select.js');
  }
}

/**
 * Implementation of hook_menu().
 */
function improved_multi_select_menu() {
  $items = array();
  $items['admin/settings/improved_multi_select'] = array(
    'title' => 'Improved Multi Select',
    'description' => 'Configure Improved Multi Select module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('improved_multi_select_admin'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Administration settings page
 */
function improved_multi_select_admin() {
  $form = array();
  $form['improved_multi_select:isall'] = array(
    '#type' => 'checkbox',
    '#title' => t('Replace all multi-select lists'),
    '#default_value' => variable_get('improved_multi_select:isall', 0),
  );
  $form['improved_multi_select:url'] = array(
    '#type' => 'textarea',
    '#title' => t('Replace multi-select lists on listed pages'),
    '#default_value' => variable_get('improved_multi_select:url', ''),
  );
  return system_settings_form($form);
}
