# Schema for the configuration files of the improved_multi_select module.

improved_multi_select.settings:
  type: mapping
  label: 'Improved Multi Select settings'
  mapping:
    isall:
      type: boolean
      label: 'Replace all multi-select lists'
    url:
      type: string
      label: 'Replace multi-select lists on specific pages'
    selectors:
      type: string
      label: 'Replace multi-select with specified selectors'
    filtertype:
      type: string
      label: 'Filter functionality'
    orderable:
      type: boolean
      label: 'Allow re-ordering of selected items'
    groupresetfilter:
      type: boolean
      label: 'Reset filter when selecting a group'
    button:
      type: mapping
      label: 'UI buttons settings'
      mapping:
        text:
          type: mapping
          label: 'Buttons texts'
          mapping:
            add:
              type: string
              label: 'Add button text'
            addall:
              type: string
              label: 'Add all button text'
            del:
              type: string
              label: 'Remove button text'
            delall:
              type: string
              label: 'Delete all button text'
            moveup:
              type: string
              label: 'Move up button text'
            movedown:
              type: string
              label: 'Move down button text'
        hint:
          type: mapping
          label: 'Buttons hints'
          mapping:
            add:
              type: string
              label: 'Add button hint'
            addall:
              type: string
              label: 'Add all button hint'
            del:
              type: string
              label: 'Remove button hint'
            delall:
              type: string
              label: 'Delete all button hint'
            moveup:
              type: string
              label: 'Move up button hint'
            movedown:
              type: string
              label: 'Move down button hint'
